"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
$username@$hostname:$directory $time
> 
'''

[time]
disabled = false
format = '[$time]($style)'

[username]
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
disabled = false
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'

[directory]
format = '[$path]($style)'
